name: pod-web
region: nyc3
services:
  - name: pod-web-app
    github:
      repo: abdelrahman-hamdy/pod-web
      branch: main
    build_command: |-
      composer install --optimize-autoloader --no-dev
      php artisan key:generate --force
      npm install
      npm run build
    run_command: php artisan serve --host 0.0.0.0 --port 8080
    http_port: 8080
    instance_count: 1
    instance_size_slug: basic-xs
    routes:
      - path: /
    envs:
      - key: APP_URL
        value: "${APP_URL}"
      - key: APP_KEY
        scope: RUN_TIME
        value: "${APP_KEY}"
      - key: DATABASE_URL
        scope: RUN_TIME
        value: "${db.DATABASE_URL}"
databases:
  - name: db
    engine: PG # PostgreSQL
    version: "12"
    num_nodes: 1
    size: db-s-1vcpu-1gb
jobs:
  - name: migrate
    kind: PRE_DEPLOY
    github:
      repo: abdelrahman-hamdy/pod-web
      branch: main
    build_command: composer install --optimize-autoloader --no-dev
    run_command: php artisan migrate:fresh --seed --force
